# Dataset Cleaning

## Import packages and load dataset

In [49]:
import pandas
import numpy as np

In [50]:
df = pandas.read_csv('model/keypoint_classifier/keypoint.csv', on_bad_lines='skip')
labels = pandas.read_csv('model/keypoint_classifier/keypoint_classifier_label.csv', header=None)

## View Dataset and Labels

In [51]:
df

,0,0.0,0.0.1,0.20078740157480315,-0.051181102362204724,0.3661417322834646,-0.18110236220472442,0.484251968503937,-0.30708661417322836,0.594488188976378,...,0.03937007874015748,-0.9763779527559056,-0.07480314960629922,-0.42913385826771655,-0.14566929133858267,-0.5787401574803149,-0.18503937007874016,-0.6850393700787402,-0.2204724409448819,-0.7874015748031497
0,0,0.0,0.0,0.206349,-0.043651,0.376984,-0.162698,0.507937,-0.273810,0.615079,...,0.047619,-0.980159,-0.079365,-0.428571,-0.142857,-0.583333,-0.182540,-0.690476,-0.210317,-0.793651
1,0,0.0,0.0,0.202381,-0.043651,0.373016,-0.162698,0.500000,-0.277778,0.607143,...,0.039683,-0.980159,-0.083333,-0.428571,-0.146825,-0.579365,-0.186508,-0.686508,-0.214286,-0.789683
2,0,0.0,0.0,0.207171,-0.039841,0.382470,-0.159363,0.509960,-0.274900,0.617530,...,0.051793,-0.980080,-0.079681,-0.426295,-0.143426,-0.581673,-0.183267,-0.689243,-0.211155,-0.792829
3,0,0.0,0.0,0.206349,-0.039683,0.380952,-0.162698,0.507937,-0.281746,0.615079,...,0.051587,-0.980159,-0.079365,-0.428571,-0.142857,-0.583333,-0.178571,-0.690476,-0.210317,-0.793651
4,0,0.0,0.0,0.206349,-0.047619,0.376984,-0.162698,0.503968,-0.273810,0.611111,...,0.051587,-0.980159,-0.079365,-0.432540,-0.142857,-0.587302,-0.178571,-0.694444,-0.206349,-0.793651
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5010,5,0.0,0.0,0.219595,-0.060811,0.395270,-0.195946,0.459459,-0.364865,0.391892,...,0.118243,-0.459459,-0.114865,-0.432432,0.003378,-0.621622,0.016892,-0.564189,0.000000,-0.483108
5011,5,0.0,0.0,0.198795,-0.105422,0.331325,-0.253012,0.373494,-0.430723,0.319277,...,0.015060,-0.472892,-0.171687,-0.385542,-0.102410,-0.566265,-0.081325,-0.521084,-0.081325,-0.439759
5012,5,0.0,0.0,0.162500,-0.140625,0.278125,-0.325000,0.271875,-0.515625,0.168750,...,-0.078125,-0.459375,-0.253125,-0.325000,-0.221875,-0.531250,-0.184375,-0.496875,-0.165625,-0.421875
5013,5,0.0,0.0,0.145215,-0.174917,0.221122,-0.396040,0.165017,-0.580858,0.042904,...,-0.174917,-0.455446,-0.333333,-0.267327,-0.330033,-0.491749,-0.283828,-0.468647,-0.250825,-0.399340
5014,5,0.0,0.0,0.119863,-0.202055,0.157534,-0.441781,0.065068,-0.626712,-0.078767,...,-0.256849,-0.421233,-0.380137,-0.229452,-0.397260,-0.458904,-0.349315,-0.417808,-0.318493,-0.349315

In [52]:
labels

            0
0        Open
1       Close
2         Erm
3          OK
4  Peace Sign
5    Fuck You

## Get rows by label

In [57]:
df.iloc[:,0]

# Get rows where label is 0
df[df.iloc[:, 0] != 3].iloc[:, 0].value_counts()

0
1    1572
0    1521
2    1356
5     149
4      80
Name: count, dtype: int64